### ISSUE TITLE
Feedback Teste TDD e BDD - Iteração 4

### ISSUE THREAD

**Issue by mateuscardosogs** [lps6/primeiroemprego#140]
Iae pessoal, vou dar o feedback dos testes TDD e BDD da iteração 4 de vocês. :)

## Testes TDD:
<ul>
  <li>Não possui nenhum caminho triste -> OK</li>
  <li>Todos os testes verdes -> OK</li>
</ul>

### Nota Final: 5
---------------------------------------------------------------

## Testes BDD:
<ul>
  <li>Possui caminho feliz/triste -> OK</li>
  <li>Todos os testes verdes -> OK</li>
</ul>

### Nota Final: 5
---------------------------------------------------------------
## Nota Final Total: 10

**Comment by phelphelps** [comment]
Boa noite. Testei novamente o rspec e TODOS os testes estão verdes. Não houve um equivoco? E também há caminhos tristes no rspec! Peço que reveja os testes da aplicação porque estão passando corretamente.

**Comment by mateuscardosogs** [comment]
@phelphelps ok, vocês poderiam me informar aonde estão codando o projeto? se localmente ou no c9, por exemplo. :)

**Comment by phelphelps** [comment]
Localmente!

**Comment by gsf4** [comment]
Boa tarde Mateus,
Alguma atualização sobre o TDD do primeiroemprego?

**Comment by mateuscardosogs** [comment]
iae pessoal, ja verifiquei o problema e foi em relação ao sistema operacional que estava na minha máquina, rodei novamente os testes e atualizei a nota de vocês. :)

**Comment by gsf4** [comment]
Obrigado Mateus
