### ISSUE TITLE
Feedback IT0

### ISSUE THREAD

**Issue by lsca** [lps6/primeiroemprego#27]
Fala galera, tudo certinho??

Corrigi usando o ultimo [commit ](https://github.com/lucaspiressilveira/primeiroemprego/tree/04dc432b827b9115a31ef33187290afd3ced387f)do dia 24.

Ata de reunião com o cliente:
Total: 10
Tópicos discutidos : -4
O que foi definido: -4
Participantes: OK
Total: 2

Mockups e storyboards:
Total: 10
Storyboard: ok
Mockup: -5
Total: 5

Preenchimento do gitHub-> 10

Postmorten: 
Não fizeram-> 0

Qualquer duvida só responder essa issue, caso contrario só fecha-la.

Sugestão adicionem uma label para feedback.

Att,

**Comment by lsca** [comment]
Ewerton - EFFS - Desenvolvedor
Gabriel - GSF4 - Desenvolvedor
Henrique - HMF- Scrum master, Engenheiro de Testes e Desenvolvedor
Lucas - LPS6 - Gerente de Projeto, Product Owner e Desenvolvedor

Quais os usuarios do git de cada um?  Ewerton é phelphelps?

**Comment by lps6** [comment]
@lsca , Ficamos só com uma dúvida, revisamos o material de aula e pesquisamos pela internet, não entendemos direito a distinção entre Lo-Fi Mockup e Lo-Fi Storyboards, até então achávamos que era a mesma coisa, mas não encontramos ao certo como distinguir para poder adicionar ao repositório.

**Comment by lsca** [comment]
Mockup é algo com mais detalhes visuais como por exemplo:
![image](https://user-images.githubusercontent.com/13456954/47027293-92befb00-d13d-11e8-992f-e11b305104dd.png)

Ja storyboard descreve mais o comportamento do teu APP/WEB Site

**Comment by lsca** [comment]
Saquem meu projeto:
https://github.com/IF977/StockZero/tree/master/Documenta%C3%A7%C3%A3o/Itera%C3%A7%C3%A3o%200

**Comment by lps6** [comment]
Show! Valeu... Já fiz e postei lá!
